name: CI/CD - Build, Push, and Deplo
 
on:
  push:
    branches: [ "main" ]
 
env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/cv_project
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
 
    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest .
 
    - name: Push image to DockerHub
      run: |
        docker push $IMAGE_NAME:${{ github.sha }}
        docker push $IMAGE_NAME:latest
 
    - name: Update deployment image
      run: |
        sed -i "s|image: .*|image: $IMAGE_NAME:${{ github.sha }}|" k8s/deployment.yml
 
    # ✅ Step 1: Set Kubernetes context
    - name: Set up Kubeconfig
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
 
    # ✅ Step 2: Deploy using kubectl
    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v5
      with:
        manifests: |
          k8s/deployment.yml
          k8s/service.yml
        images: |
          $IMAGE_NAME:${{ github.sha }}
        namespace: default
